import Link from "next/link";
import NavBar from "../components/NavBar";
import SearchHeader from "./components/SearchHeader";
import SearchSideBar from "./components/SearchSideBar";
import SearchRestaurantCard from "./components/SearchRestaurantCard";

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Search Open table',
  description: 'Generated by create next app',
  icons : {
    icon : "/icons/search.ico",
  }
}

export default function Search() {
  return (
  <>
    <SearchHeader/>
    <div className="flex py-4 m-auto w-2/3 justify-between items-start">
      <SearchSideBar/>
      <div className="w-5/6">
        <SearchRestaurantCard/>
      </div>
    </div>
  </>
  );
}
