import DetailHeader from "./components/DetailHeader";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Reataurant Open table",
  description: "Generated by create next app",
  icons : {
    icon : "/icons/reserve.ico",
  }
};

function RestaurantLayout({ children, params }: { 
  children: React.ReactNode;
  params : {slug : string}
  }) {

  return (
    <main>
      <DetailHeader name={params.slug}/>
      <div className="flex m-auto w-2/3 justify-between items-start 0 -mt-11">
        {children}
      </div>
    </main>
  );
}

export default RestaurantLayout;
