import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className ='header'>
          <div className='nav'>
            <Link href="/" className='header-title'>Homework</Link>
            <div className='header-subTitle'>
              <Link href="/write">글 작성페이지</Link>
              <Link href="/login">로그인</Link>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
