import NavigationBar from "./components/layout-page/NavigationBar";
import Logo from "./components/layout-page/Logo";
import "./globals.css";

// 웹페이지의 메타 데이터 포함 -> head태그에서 사용됨
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavigationBar />
        {children}
      </body>
    </html>
  );
}
